services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
  thirdparty:
    build: ./thirdpartymock
    ports:
      - "4000:4000"
  main_api:
    build: ./main_api
    environment:
      postgresHost: db
      posgresUser: example
      postgresPassword: example
      postgresDB: example
    ports:
      - "3200:3000"
  client:
    build: ./client
    environment:
      YOUR_API: "http://localhost:3000" # replace with your new API
    ports:
      - "3100:3100"
